name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
      - pre
  push:
    branches:
      - develop
      - pre

jobs:

  # =========================
  # BUILD AND TEST
  # =========================
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

  # =========================
  # DEPLOY DEV
  # =========================
  deploy-dev:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: DEV   # Esto habilita el approval si lo configuras en GitHub

    env:
      connected_app_client_id: ${{ vars.connected_app_client_id }}
      connected_app_client_secret: ${{ secrets.connected_app_client_secret }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Publish to Exchange
        run: |
          mvn clean deploy --settings maven/settings.xml -DskipMunitTests \
            -Dclient.id="${{ vars.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Deploy to CloudHub DEV
        run: |
          mvn mule:deploy --settings maven/settings.xml -DskipMunitTests \
            -Dclient.id="${{ vars.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Denvironment=dev
            -Dapp.name="${{ vars.APP_NAME }}"


  # =========================
  # DEPLOY PRE (con aprobación)
  # =========================
  deploy-pre:
    if: github.ref == 'refs/heads/pre' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: PRE 

    env:
      connected_app_client_id: ${{ vars.connected_app_client_id }}
      connected_app_client_secret: ${{ secrets.connected_app_client_secret }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Deploy to CloudHub PRE
        run: |
          artifact=$(ls *.jar | head -1)

          mvn mule:deploy --settings maven/settings.xml -DskipMunitTests \
            -Dmule.artifact=$artifact \
            -Dclient.id="${{ vars.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Denvironment=pre
            -Dapp.name="${{ vars.APP_NAME }}"