name: Build and Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:

  # =========================
  # BUILD + DEPLOY DEV
  # =========================
  deploy-dev:
    if: github.ref == 'refs/heads/develop'   # solo se ejecuta si es branch development
    runs-on: ubuntu-latest
    environment: DEV   # Esto habilita el approval si lo configuras en GitHub

    env:
      connected_app_client_id: ${{ vars.connected_app_client_id }}
      connected_app_client_secret: ${{ secrets.connected_app_client_secret }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      
      - name: Publish to Exchange
        run: |
          mvn clean deploy --settings maven/settings.xml -DskipMunitTests \
            -Dclient.id="${{ vars.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-app
          path: target/*.jar

      - name: Deploy to CloudHub DEV
        run: |
          mvn mule:deploy --settings maven/settings.xml -DskipMunitTests \
            -Dclient.id="${{ vars.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Denvironment=dev


  # =========================
  # DEPLOY PRE (con aprobación)
  # =========================
  deploy-pre:
    if: github.ref == 'refs/heads/main'   # solo se ejecuta si es branch main
    runs-on: ubuntu-latest
    environment: PRE 

    env:
      connected_app_client_id: ${{ vars.connected_app_client_id }}
      connected_app_client_secret: ${{ secrets.connected_app_client_secret }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-app

      - name: Deploy to CloudHub PRE
        run: |
          artifact=$(ls *.jar | head -1)

          mvn mule:deploy --settings maven/settings.xml -DskipMunitTests \
            -Dmule.artifact=$artifact \
            -Dclient.id="${{ vars.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Denvironment=pre